package main

import (
	"log"
	"os"

	"github.com/gofiber/template/html/v2"
	_ "github.com/joho/godotenv/autoload"
	"github.com/momokii/go-wa-notifier/docs"
	_ "github.com/momokii/go-wa-notifier/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/helmet"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/momokii/go-wa-notifier/internal/handlers"
)

// @title           Go Whatsapp Notifier API
// @version         1.0
// @description     -.
// @termsOfService  http://swagger.io/terms/

// @contact.name   Kelana Chandra Helyandika
// @contact.url    https://kelanach.xyz

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:3004
// @BasePath  /api
// @schemes   https

// @securityDefinitions.basic  BasicAuth

// @externalDocs.description  OpenAPI
// @externalDocs.url          https://swagger.io/resources/open-api/
func main() {
	// programmatically set swagger info
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	// * testing for using API news
	DEVMODE := os.Getenv("APP_ENV")
	PORT := os.Getenv("PORT")

	news_api_key := os.Getenv("NEWS_API_KEY")
	if news_api_key == "" {
		panic("API key is required")
	}

	// initiate handler
	newsHandler, err := handlers.NewNewsHandler(news_api_key)
	if err != nil {
		panic(err.Error())
	}

	// FIBER app initiate
	engine := html.New("./web", ".html")
	app := fiber.New(fiber.Config{
		Views: engine,
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}

			return c.Status(code).Render("error", fiber.Map{
				"Code":    code,
				"Message": err.Error(),
			})
		},
	})

	api := app.Group("/api")

	app.Use(cors.New())
	app.Use(logger.New())
	app.Use(helmet.New())
	if DEVMODE == "production" {
		app.Use(recover.New())
	}
	app.Static("/web", "./web")

	api.Get("/wa/status", newsHandler.WAStatus)
	api.Post("/news/wa", newsHandler.SendNewsAPIWhatsapp)
	api.Post("/wa/logout", newsHandler.WhatsAppLogout)

	app.Get("/", func(c *fiber.Ctx) error {
		return c.Render("status-wa", fiber.Map{
			"Title": "Go Whatsapp Notifier",
		})
	})

	if DEVMODE != "development" && DEVMODE != "production" {
		log.Println("APP_ENV not set")
	} else {
		log.Println("Running on: " + DEVMODE)
		if err := app.Listen(":" + PORT); err != nil {
			log.Println("Error running Server: ", err)
		}
	}
}
